version: '3'

services:
  node_app:
    image: srikithreddy/node_app:latest  # Pull from Docker Hub
    container_name: node_app
    ports:
      - "8080:8080"
    networks:
      - ats_network
    depends_on:
      - ats_db
      - minio

  ats_db:
    image: mysql:latest
    container_name: ats_db
    environment:
      MYSQL_ROOT_PASSWORD: Chidhagni123
      MYSQL_DATABASE: node_db
    ports:
      - "3306:3306"
    networks:
      - ats_network

  minio:
    image: minio/minio
    container_name: ats_minio
    ports:
      - "9000:9000"  # MinIO API Port
      - "9001:9001"  # MinIO Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Chidhagni@123
    command: server /data --console-address ":9001"
    networks:
      - ats_network

networks:
  ats_network:
    driver: bridge
